_target_: fragformer.lit_modules.lit_module_pretrain.FragFormerLitModule

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.005
  eps: 1e-6
  betas: [0.9, 0.999]
  weight_decay: 0.01
  _partial_: True

scheduler:
  _target_: fragformer.utils.model_utils.CosineWarmupScheduler
  _partial_: True
  warmup: 882700
  max_iters: 4413500

scheduler_interval: step